/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: firmware_package.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "firmware_package.pb-c.h"
void   firmware_upgrade__srec_line__init
                     (FirmwareUpgrade__SrecLine         *message)
{
  static const FirmwareUpgrade__SrecLine init_value = FIRMWARE_UPGRADE__SREC_LINE__INIT;
  *message = init_value;
}
size_t firmware_upgrade__srec_line__get_packed_size
                     (const FirmwareUpgrade__SrecLine *message)
{
  assert(message->base.descriptor == &firmware_upgrade__srec_line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firmware_upgrade__srec_line__pack
                     (const FirmwareUpgrade__SrecLine *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firmware_upgrade__srec_line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firmware_upgrade__srec_line__pack_to_buffer
                     (const FirmwareUpgrade__SrecLine *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firmware_upgrade__srec_line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmwareUpgrade__SrecLine *
       firmware_upgrade__srec_line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmwareUpgrade__SrecLine *)
     protobuf_c_message_unpack (&firmware_upgrade__srec_line__descriptor,
                                allocator, len, data);
}
void   firmware_upgrade__srec_line__free_unpacked
                     (FirmwareUpgrade__SrecLine *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firmware_upgrade__srec_line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   firmware_upgrade__firmware_packet__init
                     (FirmwareUpgrade__FirmwarePacket         *message)
{
  static const FirmwareUpgrade__FirmwarePacket init_value = FIRMWARE_UPGRADE__FIRMWARE_PACKET__INIT;
  *message = init_value;
}
size_t firmware_upgrade__firmware_packet__get_packed_size
                     (const FirmwareUpgrade__FirmwarePacket *message)
{
  assert(message->base.descriptor == &firmware_upgrade__firmware_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firmware_upgrade__firmware_packet__pack
                     (const FirmwareUpgrade__FirmwarePacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firmware_upgrade__firmware_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firmware_upgrade__firmware_packet__pack_to_buffer
                     (const FirmwareUpgrade__FirmwarePacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firmware_upgrade__firmware_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmwareUpgrade__FirmwarePacket *
       firmware_upgrade__firmware_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmwareUpgrade__FirmwarePacket *)
     protobuf_c_message_unpack (&firmware_upgrade__firmware_packet__descriptor,
                                allocator, len, data);
}
void   firmware_upgrade__firmware_packet__free_unpacked
                     (FirmwareUpgrade__FirmwarePacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firmware_upgrade__firmware_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   firmware_upgrade__status__init
                     (FirmwareUpgrade__Status         *message)
{
  static const FirmwareUpgrade__Status init_value = FIRMWARE_UPGRADE__STATUS__INIT;
  *message = init_value;
}
size_t firmware_upgrade__status__get_packed_size
                     (const FirmwareUpgrade__Status *message)
{
  assert(message->base.descriptor == &firmware_upgrade__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firmware_upgrade__status__pack
                     (const FirmwareUpgrade__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firmware_upgrade__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firmware_upgrade__status__pack_to_buffer
                     (const FirmwareUpgrade__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firmware_upgrade__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmwareUpgrade__Status *
       firmware_upgrade__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmwareUpgrade__Status *)
     protobuf_c_message_unpack (&firmware_upgrade__status__descriptor,
                                allocator, len, data);
}
void   firmware_upgrade__status__free_unpacked
                     (FirmwareUpgrade__Status *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firmware_upgrade__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor firmware_upgrade__srec_line__field_descriptors[5] =
{
  {
    "record_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__SrecLine, record_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "byte_count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__SrecLine, byte_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__SrecLine, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__SrecLine, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__SrecLine, checksum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firmware_upgrade__srec_line__field_indices_by_name[] = {
  2,   /* field[2] = address */
  1,   /* field[1] = byte_count */
  4,   /* field[4] = checksum */
  3,   /* field[3] = data */
  0,   /* field[0] = record_type */
};
static const ProtobufCIntRange firmware_upgrade__srec_line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor firmware_upgrade__srec_line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "firmware_upgrade.srec_line",
  "SrecLine",
  "FirmwareUpgrade__SrecLine",
  "firmware_upgrade",
  sizeof(FirmwareUpgrade__SrecLine),
  5,
  firmware_upgrade__srec_line__field_descriptors,
  firmware_upgrade__srec_line__field_indices_by_name,
  1,  firmware_upgrade__srec_line__number_ranges,
  (ProtobufCMessageInit) firmware_upgrade__srec_line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor firmware_upgrade__firmware_packet__field_descriptors[2] =
{
  {
    "checksum",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__FirmwarePacket, checksum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__FirmwarePacket, line),
    &firmware_upgrade__srec_line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firmware_upgrade__firmware_packet__field_indices_by_name[] = {
  0,   /* field[0] = checksum */
  1,   /* field[1] = line */
};
static const ProtobufCIntRange firmware_upgrade__firmware_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor firmware_upgrade__firmware_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "firmware_upgrade.firmware_packet",
  "FirmwarePacket",
  "FirmwareUpgrade__FirmwarePacket",
  "firmware_upgrade",
  sizeof(FirmwareUpgrade__FirmwarePacket),
  2,
  firmware_upgrade__firmware_packet__field_descriptors,
  firmware_upgrade__firmware_packet__field_indices_by_name,
  1,  firmware_upgrade__firmware_packet__number_ranges,
  (ProtobufCMessageInit) firmware_upgrade__firmware_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue firmware_upgrade__status__status_enum__enum_values_by_number[3] =
{
  { "READY", "FIRMWARE_UPGRADE__STATUS__STATUS_ENUM__READY", 0 },
  { "ACK", "FIRMWARE_UPGRADE__STATUS__STATUS_ENUM__ACK", 1 },
  { "REJECT", "FIRMWARE_UPGRADE__STATUS__STATUS_ENUM__REJECT", 2 },
};
static const ProtobufCIntRange firmware_upgrade__status__status_enum__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex firmware_upgrade__status__status_enum__enum_values_by_name[3] =
{
  { "ACK", 1 },
  { "READY", 0 },
  { "REJECT", 2 },
};
const ProtobufCEnumDescriptor firmware_upgrade__status__status_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "firmware_upgrade.status.status_enum",
  "status_enum",
  "FirmwareUpgrade__Status__StatusEnum",
  "firmware_upgrade",
  3,
  firmware_upgrade__status__status_enum__enum_values_by_number,
  3,
  firmware_upgrade__status__status_enum__enum_values_by_name,
  1,
  firmware_upgrade__status__status_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor firmware_upgrade__status__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FirmwareUpgrade__Status, status),
    &firmware_upgrade__status__status_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firmware_upgrade__status__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange firmware_upgrade__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor firmware_upgrade__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "firmware_upgrade.status",
  "Status",
  "FirmwareUpgrade__Status",
  "firmware_upgrade",
  sizeof(FirmwareUpgrade__Status),
  1,
  firmware_upgrade__status__field_descriptors,
  firmware_upgrade__status__field_indices_by_name,
  1,  firmware_upgrade__status__number_ranges,
  (ProtobufCMessageInit) firmware_upgrade__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
